### ISSUE TITLE
Set up kanban board for final Capstone Project

### ISSUE THREAD

**Issue by benja27** [benja27/Doctor-Appoinments---Front-End#9]
# Final capstone- Group of 4

**We separated the project into two apps, one for front end and one for back end**

## This is the front-end of the project:
- Link to front end repository => https://github.com/benja27/Doctor-Appoinments---Front-End
- Link to the front-end Kanban board => https://github.com/users/benja27/projects/14
![image](https://github.com/benja27/Doctor-Appoinments---Front-End/assets/50673336/1553dc48-4dcd-48ae-9419-c3ea03b52551)

## This is the back-end of the project:
- Link to back end repository => https://github.com/sylvester-wamaya/doctor-appointment-backend
- Link to back-end Kanban board  => https://github.com/users/sylvester-wamaya/projects/5/
![image](https://github.com/benja27/Doctor-Appoinments---Front-End/assets/50673336/bca9b16e-9dc5-4d56-a7ab-e9dc87950533)

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the Kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @benja27,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
